spring.application.name=AttendanceManagement
# ===============================
# ?? ??
# ===============================
server.port=8080

# ===============================
# MSSQL DB ??
# ===============================
spring.datasource.url=jdbc:sqlserver://211.232.94.161:1533;databaseName=SKUEDU;encrypt=false
spring.datasource.username=SKUEDU01
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# MyBatis ??
# ===============================
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.company.attendance
mybatis.configuration.map-underscore-to-camel-case=true

# ===============================
# Thymeleaf ??
# ===============================
spring.thymeleaf.cache=false

# ===============================
# ?? (????)
# ===============================
logging.level.com.company=debug
logging.level.org.mybatis=debug