server:
  port: 8080

spring:
  application:
    name: attendance-management

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://211.232.94.161:1533;databaseName=SKUEDU;encrypt=true;trustServerCertificate=true
    username: SKUEDU01
    password: "init000!"

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.company.attendancemanagement.dto
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar

logging:
  level:
    root: info
    com.company.attendancemanagement: debug
    org.mybatis: debug