DECLARE @TARGET_YYYY INT = 2026;

INSERT INTO HRTANNUALDETAIL01 (
    COMPANY, YYYY, EMP_CODE, DEPT_CODE,
    ANNUAL_START_DATE, ANNUAL_END_DATE,
    TOTAL_WORK_DAY, REAL_WORK_DAY,
    TOT_DAY, USE_DAY, BALANCE_DAY,
    CREATED_AT, UPDATED_AT
)
SELECT h.COMPANY,
       @TARGET_YYYY,
       h.EMP_CODE,
       h.DEPT_CODE,
       DATEFROMPARTS(@TARGET_YYYY, 1, 1),
       DATEFROMPARTS(@TARGET_YYYY, 12, 31),
       365,
       365,
       20,
       0,
       20,
       GETDATE(),
       GETDATE()
FROM HRIMASTER01 h
WHERE h.RETIRE_DATE IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM HRTANNUALDETAIL01 ad
      WHERE ad.COMPANY = h.COMPANY
        AND ad.YYYY = @TARGET_YYYY
        AND ad.EMP_CODE = h.EMP_CODE
  );

UPDATE HRTANNUALDETAIL01
SET USE_DAY = 0,
    BALANCE_DAY = ISNULL(TOT_DAY, 20),
    UPDATED_AT = GETDATE()
WHERE YYYY = @TARGET_YYYY;

WITH GeneralUse AS (
    SELECT r.COMPANY,
           r.TARGET_EMP_CODE AS EMP_CODE,
           CAST(SUM(
               CASE
                   WHEN r.REQ_TYPE IN ('전반차', '후반차', '오전반차', '오후반차') THEN 0.5
                   WHEN r.REQ_TYPE IN ('조퇴', '외출') AND ISNULL(plan.PLAN_WORK_MIN, 0) > 0
                       THEN CAST(ISNULL(g.WORK_MIN, 0) AS NUMERIC(19,5))
                            / CAST(plan.PLAN_WORK_MIN AS NUMERIC(19,5))
                   ELSE 0
               END
           ) AS NUMERIC(19,5)) AS USE_DAY
    FROM HRTATTENDANCEREQUEST01 r
    JOIN HRTATTENDANCE_GENERAL01 g
      ON g.COMPANY = r.COMPANY
     AND g.REQ_ID = r.REQ_ID
    OUTER APPLY (
        SELECT TOP 1
               CASE
                   WHEN s.WORK_ON_HHMM IS NULL OR s.WORK_OFF_HHMM IS NULL THEN 0
                   WHEN s.WORK_OFF_HHMM >= s.WORK_ON_HHMM
                   THEN DATEDIFF(MINUTE, s.WORK_ON_HHMM, s.WORK_OFF_HHMM)
                        - ISNULL(DATEDIFF(MINUTE, s.BREAK1_START_HHMM, s.BREAK1_END_HHMM), 0)
                        - ISNULL(DATEDIFF(MINUTE, s.BREAK2_START_HHMM, s.BREAK2_END_HHMM), 0)
                   ELSE 1440 + DATEDIFF(MINUTE, s.WORK_ON_HHMM, s.WORK_OFF_HHMM)
                        - ISNULL(DATEDIFF(MINUTE, s.BREAK1_START_HHMM, s.BREAK1_END_HHMM), 0)
                        - ISNULL(DATEDIFF(MINUTE, s.BREAK2_START_HHMM, s.BREAK2_END_HHMM), 0)
               END AS PLAN_WORK_MIN
        FROM HRIDEPTTRANSFER01 tr
        JOIN ORGDEPTMASTER01 dept
          ON dept.COMPANY = tr.COMPANY
         AND dept.DEPT_CODE = tr.DEPT_CODE
        JOIN HRTWORKPATTERNMASTER01 pm
          ON pm.COMPANY = dept.COMPANY
         AND pm.WORK_PATTERN_CODE = dept.WORK_PATTERN_CODE
         AND pm.USE_YN = 'Y'
        JOIN HRTWORKPATTERNDETAIL01 pd
          ON pd.COMPANY = pm.COMPANY
         AND pd.WORK_PATTERN_CODE = pm.WORK_PATTERN_CODE
         AND pd.SEQ = (
             (DATEDIFF(DAY, pm.START_DATE, r.TARGET_DATE) % pm.CYCLE_COUNT
              + pm.CYCLE_COUNT) % pm.CYCLE_COUNT + 1
         )
        JOIN HRTSHIFTMASTER01 s
          ON s.COMPANY = pd.COMPANY
         AND s.SHIFT_CODE = pd.SHIFT_CODE
        WHERE tr.COMPANY = r.COMPANY
          AND tr.EMP_CODE = r.TARGET_EMP_CODE
          AND tr.START_DATE <= r.TARGET_DATE
          AND (tr.END_DATE IS NULL OR tr.END_DATE >= r.TARGET_DATE)
    ) plan
    WHERE r.STATUS = 'APPROVED'
      AND r.REQ_GROUP = 'GENERAL'
      AND r.REQ_TYPE IN ('조퇴', '외출', '전반차', '후반차', '오전반차', '오후반차')
      AND YEAR(r.TARGET_DATE) = @TARGET_YYYY
    GROUP BY r.COMPANY, r.TARGET_EMP_CODE
),
OtherAnnualDays AS (
    SELECT r.COMPANY,
           r.TARGET_EMP_CODE AS EMP_CODE,
           DATEADD(DAY, n.n, o.START_DATE) AS WORK_DATE
    FROM HRTATTENDANCEREQUEST01 r
    JOIN HRTATTENDANCE_OTHER01 o
      ON o.COMPANY = r.COMPANY
     AND o.REQ_ID = r.REQ_ID
    CROSS APPLY (
        SELECT TOP (DATEDIFF(DAY, o.START_DATE, o.END_DATE) + 1)
               ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) - 1 AS n
        FROM sys.all_objects
    ) n
    WHERE r.STATUS = 'APPROVED'
      AND r.REQ_GROUP = 'OTHER'
      AND o.CHANGE_SHIFT_CODE = '06'
      AND o.START_DATE <= DATEFROMPARTS(@TARGET_YYYY, 12, 31)
      AND o.END_DATE >= DATEFROMPARTS(@TARGET_YYYY, 1, 1)
),
OtherUse AS (
    SELECT COMPANY,
           EMP_CODE,
           CAST(COUNT(*) AS NUMERIC(19,5)) AS USE_DAY
    FROM OtherAnnualDays
    WHERE YEAR(WORK_DATE) = @TARGET_YYYY
    GROUP BY COMPANY, EMP_CODE
),
TotalUse AS (
    SELECT COMPANY, EMP_CODE, SUM(USE_DAY) AS USE_DAY
    FROM (
        SELECT COMPANY, EMP_CODE, USE_DAY FROM GeneralUse
        UNION ALL
        SELECT COMPANY, EMP_CODE, USE_DAY FROM OtherUse
    ) u
    GROUP BY COMPANY, EMP_CODE
)
UPDATE ad
SET USE_DAY = CAST(ISNULL(u.USE_DAY, 0) AS NUMERIC(19,5)),
    BALANCE_DAY = ISNULL(ad.TOT_DAY, 20) - CAST(ISNULL(u.USE_DAY, 0) AS NUMERIC(19,5)),
    UPDATED_AT = GETDATE()
FROM HRTANNUALDETAIL01 ad
LEFT JOIN TotalUse u
  ON u.COMPANY = ad.COMPANY
 AND u.EMP_CODE = ad.EMP_CODE
WHERE ad.YYYY = @TARGET_YYYY;
